foreground              #bfbdb6
background              #0b0e14
selection_foreground    #bfbdb6
selection_background    #1b3a5b

cursor                  #bfbdb6
cursor_text_color       #0b0e14

# black
color0   #1e232b
color8   #686868

# red
color1   #ea6c73
color9   #f07178

# green
color2   #7fd962
color10  #aad94c

# yellow
color3   #f9af4f
color11  #ffb454

# blue
color4   #53bdfa
color12  #59c2ff

# magenta
color5   #cda1fa
color13  #d2a6ff

# cyan
color6   #90e1c6
color14  #95e6cb

# white
color7   #c7c7c7
color15  #ffffff