foreground            #D5D8DA
background            #1D1F27
selection_foreground  #D5D8DA
selection_background  #4B4C53
url_color             #FAB795

scrollback_lines 0

cursor            #D5D8DA
cursor_text_color #1D1F27

# black
color0   #1D1F27
color8   #4B4C53

# red
color1   #E95678
color9   #F43E5C

# green
color2   #27D796
color10  #21BFC2

# yellow
color3   #FAB795
color11  #FAC29A

# blue
color4   #25B2BC
color12  #75BEFF

# magenta
color5   #B877DB
color13  #B180D7

# cyan
color6   #21BFC2
color14  #25B2BC

# white
color7   #D5D8DA
color15  #D5D8DA
