foreground            #e6e6e6
background            #121212
selection_foreground  #e6e6e6
selection_background  #333333
url_color             #9ca8b0

cursor                #e6e6e6
cursor_text_color     #121212

# black 
color0  #1e1e1e
color8  #444444

# red 
color1  #b0a0a5
color9  #b0a0a5

# green
color2  #a5b0a0
color10 #a5b0a0

# yellow
color3  #b0ada0
color11 #b0ada0

# blue
color4  #9ca8b0
color12 #9ca8b0

# magenta (purple)
color5  #a89cb0
color13 #a89cb0

# cyan (aqua)
color6  #9cb0ad
color14 #9cb0ad

# white (grey tones)
color7  #888c94
color15 #b9bdc2