foreground            #d6deeb
background            #011627
selection_foreground  #011627
selection_background  #d6deeb
url_color             #57c7ff

scrollback_lines 2000

cursor                #d6deeb
cursor_text_color     #011627

# black
color0  #011627
color8  #7f97b8

# red
color1  #ff5370
color9  #ff5370

# green
color2  #9ccf69
color10 #7ee787

# yellow
color3  #ffb454
color11 #ffcb8b

# blue
color4  #82aaff
color12 #7aa2f7

# magenta
color5  #c792ea
color13 #c792ea

# cyan
color6  #2ac3de
color14 #57c7ff

# white
color7  #d6deeb
color15 #cfd3e7