foreground           #D9D7D6
background           #061115
selection_foreground #D9D7D6
selection_background #313c40
url_color            #6791C9

scrollback_lines 0

cursor           #D9D7D6
cursor_text_color #061115

# black
color0  #061115
color8  #131e22

# red
color1  #DF5B61
color9  #F16269

# green
color2  #78B892
color10 #8CD7AA

# yellow
color3  #ecd28b
color11 #f6dc95

# blue
color4  #6791C9
color12 #79AAEB

# magenta
color5  #C488EC
color13 #BC83E3

# cyan
color6  #67AFC1
color14 #7ACFE4

# white
color7  #4f5a5e
color15 #D9D7D6